### ISSUE TITLE
poem doesn't support copy.deepcopy()

### ISSUE THREAD

**Issue by pmineiro** [microsoft/LLF-Bench#6]
maybe other environments also have this problem, i haven't tried.

(the random generator state needs to be copied in a custom `__deepcopy__` hook ...)

**Comment by pmineiro** [comment]
looks like upstream gym has a fix, but the setup.py is demanding an older version of gym

**Comment by chinganc** [comment]
Thanks @pmineiro. I will look into this.

**Comment by pmineiro** [comment]
cool.  it would be good to add unit tests asserting that all environments can be deepcopied, as this is important for algorithms that compute advantages.

**Comment by chinganc** [comment]
@pmineiro  It's now fixed with commit 2a861e00601471b58ecb88cf8d61effdb94a051e.
