### ISSUE TITLE
Environment name error

### ISSUE THREAD

**Issue by BeibinLi** [microsoft/LLF-Bench#8]
Following the README file and running the following code with the latest version would yield error: Environment `llf-Gridworld-v0` doesn't exist.

```python
import llfbench as gym
env = gym.make('llf-Gridworld-v0')
```

I looked into the `__init__` file, line 5 is causing the issue `env = gym.make(env_name)`, where the "gym" is the gymnasium rather than llf-bench.

**Comment by chinganc** [comment]
@BeibinLi  The code is okay, just the registered env_name is `llf-gridworld-v0`. Can you give it a try?

**Comment by BeibinLi** [comment]
Thanks! The new env name fixed the issue.
