### ISSUE TITLE
Missing code for alfworld and meta world

### ISSUE THREAD

**Issue by dong-river** [microsoft/LLF-Bench#9]
Thanks for the interesting work. I try to use this repo, but for alfworld and meta world, there seems many packages are missing. For example, in the screenshot, there's no alfworld.agents in the file system but the code try to import it. I think you used the code from alfworld directly but somehow deleted some directories. Could you please fix that? Thank [you!]
<img width="1005" alt="Screen Shot 2024-02-22 at 9 41 05 AM" src="https://github.com/microsoft/LLF-Bench/assets/124754415/8a35deef-7586-4f78-bcd8-e6a67a3d1e08">

**Comment by chinganc** [comment]
Hi @dong-river, using alfworld and metaworld requires passing additional arguments to pip when you install the repo, e.g. by running `pip install -e.[metaworld]`. Depending on your setup, there may be additional dependencies needed. After that, the needed packages will be installed. Please see the README for more details. Thanks.

**Comment by dkmisra** [comment]
Hi @dong-river were you able to resolve this? You need to run

`pip install -e . [alfworld]` and use python 3.9. Please see the updated instructions for alfworld in README.md.

**Comment by chinganc** [comment]
I suppose this issue has been resolved. I will close this issue.
